### ISSUE TITLE
Mutator List filtering

### ISSUE THREAD

**Issue by Freiling87** [Chasmical/RogueLibs#75]
### Describe the problem

Created Mutator Unlocks appear in all versions of the menu (Campaign, Level, and Home Base).

### Describe the solution

Add virtual (true) bools to MutatorUnlock:
- AppearsInCampaignMutatorList
- AppearsInHomeBaseMutatorList
- AppearsInLevelMutatorList

Vanilla code targets:
- Campaign: LevelEditor.CreateMutatorListCampaign
- Home Base: ScrollingMenu.SortUnlocks
- Level: LevelEditor.CreateMutatorListLevel

**Comment by Chasmical** [comment]
## ⚰️ RogueLibs has been discontinued ⚰️

The project's repository is archived as part of the GitHub Archive Program. RogueLibs' code and the documentation will no longer be updated. See more information in the [latest blog post](https://chasmical.github.io/RogueLibs/blog/2024/02/03/discontinuing-roguelibs). Feel free to fork the repository to continue working on the project.

**Comment by Chasmical** [comment]
## ⚰️ RogueLibs has been discontinued ⚰️

The project's repository is archived as part of the GitHub Archive Program. RogueLibs' code and the documentation will no longer be updated. See more information in the [latest blog post](https://chasmical.github.io/RogueLibs/blog/2024/02/03/discontinuing-roguelibs). Feel free to fork the repository to continue working on the project.
