### ISSUE TITLE
Trait/Mutator Conflicts

### ISSUE THREAD

**Issue by Freiling87** [Chasmical/RogueLibs#76]
### Describe the problem

There's currently no simple way to register conflicts between Traits and Mutators. Some traits might be pointless for a player to take with a certain mutator. E.g., Lock & Load + Unlimited Ammo.

### Describe the solution

Add lists to 

Relevant vanilla code: ScrollingMenu.CanHaveTrait

**Comment by Chasmical** [comment]
## ⚰️ RogueLibs has been discontinued ⚰️

The project's repository is archived as part of the GitHub Archive Program. RogueLibs' code and the documentation will no longer be updated. See more information in the [latest blog post](https://chasmical.github.io/RogueLibs/blog/2024/02/03/discontinuing-roguelibs). Feel free to fork the repository to continue working on the project.
